### ISSUE TITLE
Could you provide the results after the setup_dataset_kitti.py, please?

### ISSUE THREAD

**Issue by Jue-Jue-511** [alexklwong/calibrated-backprojection-network#1]
Thank you very much for providing this code！
but i still have a little question :
The path you provide in the setup_dataset_kitti.py doesn't seem to be an dirpath, so there were a lot of empty txt files  after I ran the code.
in line 258 :
sequence = sparse_depth_paths[0].split(os.sep)[5]
sequence_date = sequence[0:10]
When I debug the code，the sequence is 'data'  so the sequence_data is 'data'  but i think its wrong 
im look forward to your answer

**Comment by alexklwong** [comment]
Can you provide your data directory hierarchy?
You can do something like

ls data/
ls data/kitti_raw_data
ls data/kitti_depth_completion

**Comment by Jue-Jue-511** [comment]
(base) juejue@hzd:/home/data/JueJue/calibrated-backprojection-network$ ls data/
kitti_depth_completion  kitti_raw_data
(base) juejue@hzd:/home/data/JueJue/calibrated-backprojection-network$ ls data/kitti_raw_data
2011_09_26  2011_09_28  2011_09_29  2011_09_30  2011_10_03  data_splits  LICENSE.md
(base) juejue@hzd:/home/data/JueJue/calibrated-backprojection-network$ ls data/kitti_depth_completion
testing  train_val_split  validation

**Comment by Jue-Jue-511** [comment]
thank u for ur reply ,i have found the problem 

mv /home/data/JueJue/calibrated-backprojection-network/setup/setup_dataset_kitti.py 
/home/data/JueJue/calibrated-backprojection-network/

after this action , the program is work

**Comment by alexklwong** [comment]
Strange, the base directories seem to match 

I just ran the set up locally and it worked. Maybe some subdirectories do not match.

Can you print
print(sparse_depth_paths[0:5])
at
https://github.com/alexklwong/calibrated-backprojection-network/blob/master/setup/setup_dataset_kitti.py#L251

and also print
print(sequence, sequence_date)
print(raw_sequence_dirpath)
print(image_paths[0:5])
at
https://github.com/alexklwong/calibrated-backprojection-network/blob/master/setup/setup_dataset_kitti.py#L268)

**Comment by alexklwong** [comment]
Was your data folder inside calibrated-backprojection-network?

**Comment by Jue-Jue-511** [comment]
my data folder is ./calibrated-backprojection-network/data/
and the setup_dataset_kitti.py path is  ./calibrated-backprojection-network/setup/setup_dataset_kitti.py 
when i run the python file ,the The current path is ./calibrated-backprojection-network/setup/....
for example 

> KITTI_RAW_DATA_DIRPATH = os.path.join('data', 'kitti_raw_data')

the result is  data/kitti_raw_data   the abspath is ./calibrated-backprojection-network/setup/data/kitti_raw_data
which is wrong 
when i move setup_dataset_kitti.py to  ./calibrated-backprojection-network/setup_dataset_kitti.py
the abspath is  ./calibrated-backprojection-network/data/kitti_raw_data  
whcih is right

**Comment by alexklwong** [comment]
Ah I see, for the setup scripts I assume that you are inside the base directory of the repository (calibrated-backprojection-network) e.g.

calibrated-backprojection-network <----- run the commands while you are inside this folder here
|
|----- data
|----- setup
|----- src
