### ISSUE TITLE
How to get the beautiful demo?

### ISSUE THREAD

**Issue by hillaric** [alexklwong/calibrated-backprojection-network#17]
In the given demo, you have a sparse points and colored predicted point clouds, I want to know how to get the similar demo?

**Comment by alexklwong** [comment]
Hi, sorry for the late response, I've been traveling for conferences. 

I backprojected the depth map into point clouds using the intrinsics and used [MeshLab](https://www.meshlab.net/)  to open them. I recorded the gifs with [Peek](https://www.linuxfordevices.com/tutorials/linux/install-peek-on-linux)
