### ISSUE TITLE
Questionable depth map on VOID ground truth + inference

### ISSUE THREAD

**Issue by DornAres** [alexklwong/calibrated-backprojection-network#20]
Hey there!
Thank you for the work!
I tried it out on my own sparse depth map + rgb image, and it didn't perform too well at all. I also visualized some ground truth data from the VOID dataset, and found that some pointclouds look similarly bad. The _copyroom_ folder looks fine, but the first image from _birthplace_of_internet_ already looks bad. I can understand my own dataset could be problematic concerning sparse depth map resolution, but after looking at some ground truth data, I'm wondering if the problem lies elsewhere. 

Any idea on why my custom dataset would look like this? The "bad" ground truth from VOID still looks better than my results .
[Here a link](https://imgur.com/a/v6hHQB6) to the visualization of a VOID and a custom pointcloud.

I ran kbnet on both a Python 3.7 venv with the given dependency versions and a 3.9 venv with newer library versions.

I visualized everything using Open3D:

```
        image_opencv = cv2.imread(image_file)
        image = o3d.io.read_image(image_file)
        depth_image = o3d.io.read_image(depth_file)
        K = np.loadtxt(intrinsics_file)
        intrinsic = o3d.camera.PinholeCameraIntrinsic(image_opencv.shape[0], image_opencv.shape[1], K[0][0],K[1][1], K[0][2], K[1][2])
        rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(image, depth_image, convert_rgb_to_intensity=False)
        pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image, intrinsic)
        o3d.visualization.draw_geometries([pcd])

```

**Comment by alexklwong** [comment]
Hi, thanks for the interest!
Just to make sure:
Is the visualization you are showing the ground truth? Are you using the depth maps that were unzipped after downloaded from the Google Drive?

Also, the way that depth maps are loaded and stored is using data_utils. Have you tried that?
https://github.com/alexklwong/calibrated-backprojection-network/blob/master/src/data_utils.py#L123

**Comment by alexklwong** [comment]
Also, one thing to note is that the depth maps have "holes" of missing regions due to occlusions, reflectivity, etc., which when backprojected will create "spikes" towards the camera. So it helps to interpolate the missing regions using something like:
https://github.com/alexklwong/unsupervised-depth-completion-visual-inertial-odometry/blob/master/src/data_utils.py#L178

before you visualize them.

**Comment by alexklwong** [comment]
I think this may be a pytorch version issue, for instance:
https://github.com/alexklwong/calibrated-backprojection-network/issues/7#issuecomment-998527719
https://github.com/alexklwong/calibrated-backprojection-network/issues/8#issuecomment-1095340419

What version of Ubuntu, CUDA, PyTorch version are you using? Also which GPU are you using?

**Comment by DornAres** [comment]
I also that's it, although I've tried out some options already.

Ubuntu 20.04, RTX 3080, CUDA Driver version 510.47.03, CUDA Toolkit 11.3

I tried out the following venvs:
Python 3.7, torch==1.8.2+cu111 (the 2nd installation way from the README)
Python 3.9, torch==1.8.2+cu111
Python 3.9, torch==1.11.0+cu113

I'm considering downgrading to CUDA 11.1 but not sure if worth the hassle considering it should be compatible with the torch binaries and the fact is still gets the same results using torch 1.11 for CUDA 11.3

**Comment by alexklwong** [comment]
Hi, we did a number of experiments with different CUDA and pytorch versions.

What we found is that for the RTX family. The ones that seem to work well is

Python 3.8, torch==1.8.0+cu111
Python 3.8, torch==1.9.1+cu111

1.8.1 will not work because they introduced a bug in indexing slices, causing errors to be thrown.
Note that 1.8.0 and 1.9.1 are also compatible with CUDA 11.3

**Comment by DornAres** [comment]
Thank you! It does seem to perform consistently better now.
