### ISSUE TITLE
min/max_predict_depth

### ISSUE THREAD

**Issue by 2016choang** [alexklwong/calibrated-backprojection-network#22]
Hello Alex, thank you for releasing this work!

I had a quick question: what is the purpose of min_predict_depth and max_predict_depth / what do these two lines do? [https://github.com/alexklwong/calibrated-backprojection-network/blob/master/src/kbnet_model.py#L183-L184](https://github.com/alexklwong/calibrated-backprojection-network/blob/master/src/kbnet_model.py#L183-L184)

From my interpretation, it does not seem to be scaling the output_depth to be between the min_predict_depth and max_predict_depth.

Thank you!

**Comment by alexklwong** [comment]
Hi, this is just a way to treat the output_depth variable as inverse depth but keep it within the approximate range of min and max predict depth
