### ISSUE TITLE
Why quality is so bad? 

### ISSUE THREAD

**Issue by denred0** [alexklwong/calibrated-backprojection-network#25]
Hi! 

Thanks for your great work! I have tested your repository and got bad results. 
I tested with bash/void/run_kbnet_void150.sh 

There is the image
![0000000043](https://user-images.githubusercontent.com/8546089/233640883-6728a209-ac24-4613-ac0e-4c28786cbbff.png)

Depth map:
![grayscale](https://user-images.githubusercontent.com/8546089/233641544-7cf394a6-383b-4764-8476-60482173b8e7.png)

Sparse point cloud:
![screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023 04 21-17_50_16](https://user-images.githubusercontent.com/8546089/233640672-f71e929b-9a06-4c0e-82ff-812e3efe72f9.gif)

And resulting dense point cloud:
![screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023 04 21-17_53_47](https://user-images.githubusercontent.com/8546089/233641227-8443518e-9389-4791-ac32-e66347e2aa34.gif)

Looks much worse than in your README. Is it normal or I don't know about additional postprocessing?
Thanks.

**Comment by alexklwong** [comment]
Hi, looks like there are some issues with torch version and CUDA affecting training and inference. Previously, it was done with GTX family. We are now retraining on RTX with torch 1.10 and will upload the weights.
