### ISSUE TITLE
Issue Accessing Google Drive Links for Dataset Downloads

### ISSUE THREAD

**Issue by MEKSAAA** [alexklwong/calibrated-backprojection-network#28]
Hello Alex,

I am currently trying to replicate the experiments from your repository, but I am encountering issues with the Google Drive links provided for downloading the datasets (KITTI, NYUv2, and VOID). Unfortunately, I cannot access any of the links, and they seem to be 
broken or restricted.

Could you please provide alternative download methods or updated links for these datasets? This would greatly help me and others who are trying to use your code.

Thank you for your assistance!

**Comment by alexklwong** [comment]
Hi,

I have updated Google Drive links to OneDrive/SharePoint for VOID and NYYv2. For KITTI,  `bash/kitti/setup_dataset_kitti.sh` is the download script for KITTI, but I believe they may have changed their policy and requires log in for download, so you will need to follow their instructions. Once you have downloaded KITTI (data_depth_velodyne.zip, data_depth_selection.zip, data_depth_annotated.zip) from their Amazon S3 bucket, you can use the following commands taken from bash/kitti/setup_dataset_kitti.sh

```
mkdir -p data/kitti_depth_completion
mkdir -p data/kitti_depth_completion/train_val_split
mkdir -p data/kitti_depth_completion/train_val_split/sparse_depth
mkdir -p data/kitti_depth_completion/train_val_split/ground_truth
mkdir -p data/kitti_depth_completion/validation
mkdir -p data/kitti_depth_completion/testing
mkdir -p data/kitti_depth_completion/tmp

unzip data/data_depth_velodyne.zip -d data/kitti_depth_completion/train_val_split/sparse_depth
unzip data/data_depth_annotated.zip -d data/kitti_depth_completion/train_val_split/ground_truth
unzip data/data_depth_selection.zip -d data/kitti_depth_completion/tmp

mv data/kitti_depth_completion/tmp/depth_selection/val_selection_cropped/image data/kitti_depth_completion/validation/image
mv data/kitti_depth_completion/tmp/depth_selection/val_selection_cropped/velodyne_raw data/kitti_depth_completion/validation/sparse_depth
mv data/kitti_depth_completion/tmp/depth_selection/val_selection_cropped/groundtruth_depth data/kitti_depth_completion/validation/ground_truth
mv data/kitti_depth_completion/tmp/depth_selection/val_selection_cropped/intrinsics data/kitti_depth_completion/validation/intrinsics

mv data/kitti_depth_completion/tmp/depth_selection/test_depth_completion_anonymous/image data/kitti_depth_completion/testing/image
mv data/kitti_depth_completion/tmp/depth_selection/test_depth_completion_anonymous/velodyne_raw data/kitti_depth_completion/testing/sparse_depth
mv data/kitti_depth_completion/tmp/depth_selection/test_depth_completion_anonymous/intrinsics data/kitti_depth_completion/testing/intrinsics

rm -r data/kitti_depth_completion/tmp

python setup/setup_dataset_kitti.py
```

**Comment by MEKSAAA** [comment]
Thank you sooo much!!! It helps a lot!!! I have successfully downloaded datasets.
