### ISSUE TITLE
A bug in setup_dataset_nyu_v2.sh

### ISSUE THREAD

**Issue by MingkangXiong** [alexklwong/calibrated-backprojection-network#6]
https://github.com/alexklwong/calibrated-backprojection-network/blob/57dbec03c6da94ee0cd020b6de5f02e7e8ee726e/bash/nyu_v2/setup_dataset_nyu_v2.sh#L6

The last comma needs to be removed.

**Comment by alexklwong** [comment]
Thanks for catching that, it seems that the setup_dataset_nyu_v2.sh script is not the most updated version. There were additional commands to set up the dataset as we used it. I am not in town right now, but will push an update soon.
