### ISSUE TITLE
about NYUv2 data

### ISSUE THREAD

**Issue by lqzhao** [alexklwong/calibrated-backprojection-network#9]
Hi Alex, 
I notice that you update the script for downloading the NYUv2 dataset. Thanks.
I downloaded the raw data from the NYUv2 official website weeks ago. But I found the unzipped data contains many files, with extensions like: '.dump', '.pgm', and '.ppm'. 
And the name of files are like:
![image](https://user-images.githubusercontent.com/43566465/153228231-214bc146-76ce-4a43-a2cf-3790c0020f4e.png)

However, the setup python file of NYUv2 seems to only accept the files with '.png' extension.
https://github.com/alexklwong/calibrated-backprojection-network/blob/73e3943169b3baf0e5b60e1b3378337245a03464/setup/setup_dataset_nyu_v2.py#L246

So my question is: Did I download the correct NYUv2 data? or How can I set up the data for your code?
Thanks in advance!

**Comment by alexklwong** [comment]
Ah I just realized that our lab's internal copy of NYUv2 has been post processed and synced. I will write a setup to do that post processing and synchronization. That might be valuable for anyone who wants to work on NYUv2.

**Comment by lqzhao** [comment]
> Ah I just realized that our lab's internal copy of NYUv2 has been post processed and synced. I will write a setup to do that post processing and synchronization. That might be valuable for anyone who wants to work on NYUv2.

That's great, thank you for your effort.

**Comment by alexklwong** [comment]
Sorry this took so long, we will upload the preprocessed version of NYUv2 onto Google drive.

**Comment by alexklwong** [comment]
@lqzhao here are the new instructions for setting up NYUv2. We've synchronized and aligned the depth and image frames and stored it into a zip. You can follow the README to download and set up the dataset.
 
https://github.com/alexklwong/calibrated-backprojection-network/tree/nyu-v2-setup

This will be merged into master shortly.

**Comment by lqzhao** [comment]
Thank you~
